parameters:
  mybundle.controller.affiliate_controller.class: MyBundle\Controller\AffiliateController
  mybundle.controller.api_controller.class: MyBundle\Controller\ApiController
  mybundle.controller.category_controller.class: MyBundle\Controller\CategoryController
  mybundle.controller.category_admin_controller.class: MyBundle\Controller\CategoryAdminController
  mybundle.controller.default_controller.class: MyBundle\Controller\DefaultController
  mybundle.controller.job_admin_controller.class: MyBundle\Controller\JobAdminController
  mybundle.controller.job_controller.class: MyBundle\Controller\JobController

services:
  mybundle.controller.affiliate_controller:
    class: %mybundle.controller.affiliate_controller.class%
    arguments:
      - @mybundle.manager.affiliate_manager
      - @form.factory
      - @templating
      - @router

  mybundle.controller.api_controller:
    class: %mybundle.controller.api_controller.class%
    arguments:
      - @mybundle.provider.affiliate_provider
      - @mybundle.provider.job_provider

  mybundle.controller.category_controller:
    class: %mybundle.controller.category_controller.class%
    arguments:
      - @mybundle.provider.affiliate_provider
      - @mybundle.provider.job_provider

  mybundle.controller.category_admin_controller:
    class: %mybundle.controller.category_admin_controller.class%

  mybundle.controller.default_controller:
    class: %mybundle.controller.default_controller.class%

  mybundle.controller.job_admin_controller:
    class: %mybundle.controller.job_admin_controller.class%
    arguments:
      - @mybundle.provider.job_provider

  mybundle.controller.job_controller:
    class: %mybundle.controller.job_controller.class%
    arguments:
      - @mybundle.manager.jobManager
      - @mybundle.provider.categoryProvider
    calls:
      - [setContainer, ['@service_container']]
