parameters:
  mybundle.event_listener.notice_listener.class: MyBundle\EventListener\NoticePagerListener

services:
  mybundle.controller.notice_listener:
    class: %mybundle.event_listener.notice_listener.class%
    tags:
      - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
