ShepardBundle_affiliate:
    resource: "@MyBundle/Resources/config/routing/affiliate.yml"
    prefix:   /affiliate

ShepardBundle_job:
    resource: "@MyBundle/Resources/config/routing/job.yml"
    prefix:   /job

ShepardBundle_homepage:
    pattern:  /
    defaults: { _controller: mybundle.controller.job_controller:indexAction }

ShepardBundle_category:
    pattern: /category/{slug}/{page}
    defaults: { _controller: mybundle.controller.category_controller:showAction, page: 1 }
    requirements: { _method: get }

ShepardBundle_login:
    pattern:   /login
    defaults:  { _controller: MyBundle:Default:login }

ShepardBundle_login_check:
    pattern:   /login_check

ShepardBundle_logout:
    pattern:   /logout

ShepardBundle_api:
    pattern: /api/{token}/jobs.{_format}
    defaults: {_controller: MyBundle:Api:list}
    requirements:
        _format: xml|json|yaml
