services:
    ens.admin.category:
        class: MyBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: jobeet, label: Categories }
        arguments: [null, MyBundle\Entity\Category, MyBundle:CategoryAdmin]
 
    ens.admin.job:
        class:  MyBundle\Admin\JobAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: jobeet, label: Jobs }
        arguments: [null,  MyBundle\Entity\Job, MyBundle:JobAdmin]
