ShepardBundle_affiliate_new:
    pattern:  /new
    defaults: { _controller: ShepardBundle.controller.affiliate_controller:newAction }

ShepardBundle_affiliate_create:
    pattern: /create
    defaults: { _controller: ShepardBundle.controller.affiliate_controller:createAction }
    requirements: { _method: post }

ShepardBundle_affiliate_wait:
    pattern: /wait
    defaults: { _controller: ShepardBundle.controller.affiliate_controller:waitAction }
