fos_elastica:
    clients:
        default: { host: %elastic_host%, port: %elastic_port% }
    indexes:
        jobeet_bundle:
            client: default
            types:
                job:
                    mappings:
                      company:
                        type: string
                        length: 255
                      position:
                        type: string
                        length: 255
                      location:
                        type: string
                        length: 255
                      description:
                        type: string
                      email:
                        type: string
                        length: 255
                    persistence:
                        driver: orm
                        model: ShepardBundle\Entity\Job
                        finder: ~
                        provider: ~
                        listener: ~
