fos_elastica:
    clients:
        default: { host: %elastic_host%, port: %elastic_port% }
    indexes:
        jobeet_bundle:
            client: default
            types:
                job:
                    mappings:
                      type:
                        type: string
                        length: 255
                        nullable: true
                      company:
                        type: string
                        length: 255
                      logo:
                        type: string
                        length: 255
                        nullable: true
                      url:
                        type: string
                        length: 255
                        nullable: true
                      position:
                        type: string
                        length: 255
                      location:
                        type: string
                        length: 255
                      description:
                        type: string
                      how_to_apply:
                        type: string
                      token:
                        type: string
                        length: 255
                        unique: true
                      is_public:
                        type: boolean
                        nullable: true
                      is_activated:
                        type: boolean
                        nullable: true
                      email:
                        type: string
                        length: 255
                      expires_at:
                        type: date
                      created_at:
                        type: date
                      updated_at:
                        type: date
                        nullable: true
                    persistence:
                        driver: orm
                        model: ShepardBundle\Entity\Job
                        finder: ~
                        provider: ~
                        listener: ~
