parameters:
  jobeet.mybundle.controller.affiliate_controller.class: jobeet\MyBundle\Controller\AffiliateController
  jobeet.mybundle.controller.api_controller.class: jobeet\MyBundle\Controller\ApiController
  jobeet.mybundle.controller.category_controller.class: jobeet\MyBundle\Controller\CategoryController
  jobeet.mybundle.controller.category_admin_controller.class: jobeet\MyBundle\Controller\CategoryAdminController
  jobeet.mybundle.controller.default_controller.class: jobeet\MyBundle\Controller\DefaultController
  jobeet.mybundle.controller.job_admin_controller.class: jobeet\MyBundle\Controller\JobAdminController
  jobeet.mybundle.controller.job_controller.class: jobeet\MyBundle\Controller\JobController

services:
  jobeet.mybundle.controller.affiliate_controller:
    class: %jobeet.mybundle.controller.affiliate_controller.class%
    arguments: [@jobeet.mybundle.manager.affiliate_manager]

  jobeet.mybundle.controller.api_controller:
    class: %jobeet.mybundle.controller.api_controller.class%
    arguments: [@jobeet.mybundle.provider.affiliate_provider, @jobeet.mybundle.provider.job_provider]

  jobeet.mybundle.controller.category_controller:
    class: %jobeet.mybundle.controller.category_controller.class%
    arguments: [@jobeet.mybundle.provider.affiliate_provider, @jobeet.mybundle.provider.job_provider]

  jobeet.mybundle.controller.category_admin_controller:
    class: %jobeet.mybundle.controller.category_admin_controller.class%

  jobeet.mybundle.controller.default_controller:
    class: %jobeet.mybundle.controller.default_controller.class%

  jobeet.mybundle.controller.job_admin_controller:
    class: %jobeet.mybundle.controller.job_admin_controller.class%
    arguments: [@jobeet.mybundle.provider.job_provider]

  jobeet.mybundle.controller.job_controller:
    class: %jobeet.mybundle.controller.job_controller.class%
    arguments: [@jobeet.mybundle.provider.job_provider, @jobeet.mybundle.provider.category_provider]
