parameters:
  jobeet.mybundle.manager.manager.class: jobeet\MyBundle\Manager\Manager
  jobeet.mybundle.manager.job.class: jobeet\MyBundle\Entity\Job
  jobeet.mybundle.manager.job_repository.path: MyBundle:Job
  jobeet.mybundle.manager.affiliate.class: jobeet\MyBundle\Entity\Affiliate
  jobeet.mybundle.manager.affiliate_repository.path: MyBundle:Affiliate
  jobeet.mybundle.manager.category.class: jobeet\MyBundle\Entity\Category
  jobeet.mybundle.manager.category_repository.path: MyBundle:Category

services:
  jobeet.mybundle.manager.job_manager:
    class: %jobeet.mybundle.manager.manager.class%
    arguments:
      - @doctrine.orm.entity_manager
      - @jobeet.mybundle.cache_driver.driver
      - %jobeet.mybundle.manager.job.class%
      - %jobeet.mybundle.manager.job_repository.path%

  jobeet.mybundle.manager.affiliate_manager:
    class: %jobeet.mybundle.manager.manager.class%
    arguments:
      - @doctrine.orm.entity_manager
      - @jobeet.mybundle.cache_driver.driver
      - %jobeet.mybundle.manager.affiliate.class%
      - %jobeet.mybundle.manager.affiliate_repository.path%

  jobeet.mybundle.manager.category_manager:
    class: %jobeet.mybundle.manager.manager.class%
    arguments:
      - @doctrine.orm.entity_manager
      - @jobeet.mybundle.cache_driver.driver
      - %jobeet.mybundle.manager.category.class%
      - %jobeet.mybundle.manager.category_repository.path%
