my_ens_job:
    resource: "@MyBundle/Resources/config/routing/job.yml"
    prefix:   /ens_job

my_homepage:
    path:     /hello/{name}
    defaults: { _controller: MyBundle:Default:index }

EnsJobeetBundle_job:
    resource: "@MyBundle/Resources/config/routing/job.yml"
    prefix: /job

EnsJobeetBundle_homepage:
    pattern:  /
    defaults: { _controller: MyBundle:Job:index }
