my_ens_job:
    resource: "@MyBundle/Resources/config/routing/job.yml"
    prefix:   /ens_job

my_homepage:
    path:     /hello/{name}
    defaults: { _controller: MyBundle:Default:index }

EnsJobeetBundle_job:
    resource: "@MyBundle/Resources/config/routing/job.yml"
    prefix: /job

EnsJobeetBundle_homepage:
    pattern:  /
    defaults: { _controller: MyBundle:Job:index }

EnsJobeetBundle_category:
    pattern: /category/{slug}/{page}
    defaults: { _controller: MyBundle:Category:show, page: 1  }

ens_job_edit:
    pattern:  /{token}/edit
    defaults: { _controller: "MyBundle:Job:edit" }

ens_job_update:
    pattern:  /{token}/update
    defaults: { _controller: "MyBundle:Job:update" }
    requirements: { _method: post }

ens_job_delete:
    pattern:  /{token}/delete
    defaults: { _controller: "MyBundle:Job:delete" }
    requirements: { _method: post }

login:
    pattern:   /login
    defaults:  { _controller: MyBundle:Default:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

ens_api:
    pattern: /api/{token}/jobs.{_format}
    defaults: {_controller: "MyBundle:Api:list"}
    requirements:
        _format: xml|json|yaml

MyBundle_affiliate:
    resource: "@MyBundle/Resources/config/routing/affiliate.yml"
    prefix:   /affiliate
