services:
    ens.jobeet.admin.category:
        class: jobeet\MyBundle\Admin\CategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: jobeet, label: Categories }
        arguments: [null, jobeet\MyBundle\Entity\Category, MyBundle:CategoryAdmin]
 
    ens.jobeet.admin.job:
        class:  jobeet\MyBundle\Admin\JobAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: jobeet, label: Jobs }
        arguments: [null,  jobeet\MyBundle\Entity\Job, MyBundle:JobAdmin]
