ens_job:
    path:     /
    defaults: { _controller: "MyBundle:Job:index" }

ens_job_show:
    pattern:  /{company}/{location}/{id}/{position}
    defaults: { _controller: "MyBundle:Job:show" }
    requirements:
        id:  \d+

ens_job_new:
    path:     /new
    defaults: { _controller: "MyBundle:Job:new" }

ens_job_create:
    path:     /create
    defaults: { _controller: "MyBundle:Job:create" }
    methods:  POST

ens_job_edit:
    path:     /{id}/edit
    defaults: { _controller: "MyBundle:Job:edit" }

ens_job_update:
    path:     /{id}/update
    defaults: { _controller: "MyBundle:Job:update" }
    methods:  [POST, PUT]

ens_job_delete:
    path:     /{id}/delete
    defaults: { _controller: "MyBundle:Job:delete" }
    methods:  [POST, DELETE]

ens_job_show:
    pattern:  /{company}/{location}/{id}/{position}
    defaults: { _controller: "MyBundle:Job:show" }
    requirements:
        id:  \d+

ens_job_preview:
    pattern:  /{company}/{location}/{token}/{position}
    defaults: { _controller: "MyBundle:Job:preview" }
    requirements:
        token:  \w+

ens_job_publish:
    pattern:  /{token}/publish
    defaults: { _controller: "MyBundle:Job:publish" }
    requirements: { _method: post }

ens_job_extend:
    pattern:  /{token}/extend
    defaults: { _controller: "MyBundle:Job:extend" }
    requirements: { _method: post }
